name: Maven Package

on:
  push:
    branches: '*'  # Срабатывает на пуш в любую ветку
  pull_request:
    branches: '*'  # Срабатывает на PR в любую ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Запускается на Ubuntu в облаке
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run mvn package
        run: |
          mvn clean package